name: Scheduled FitBot run

on:
  schedule:
  - cron: "01 16 * * *"
  workflow_dispatch: # <--- ESTA LÍNEA ES LA QUE ACTIVA EL BOTÓN MANUAL

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run FitBot Docker Image
        run: |
          docker run \
            -e email="${{ secrets.EMAIL }}" \
            -e password="${{ secrets.PASSWORD }}" \
            -e box-name="${{ vars.BOX_NAME }}" \
            -e box-id="${{ vars.BOX_ID }}" \
            -e booking-goals='${{ vars.BOOKING_GOALS }}' \
            -e days-in-advance="${{ vars.DAYS_IN_ADVANCE }}" \
            pablobuenaposada/fitbot
